-- ============================================================================
-- EcoRoute: MySQL -> Supabase (PostgreSQL) migration
-- Generated from local `ecoroute` MySQL database on 2026-09-07.
-- Run this whole file once in the Supabase SQL editor (or via psql) against
-- a fresh Supabase project. It creates the schema and loads the existing data.
-- ============================================================================

begin;

-- Drop in FK-safe order in case of re-run
drop table if exists waypoints cascade;
drop table if exists routes cascade;
drop table if exists vehicles cascade;
drop table if exists passwords cascade;
drop table if exists users cascade;

-- ----------------------------------------------------------------------------
-- users
-- ----------------------------------------------------------------------------
create table users (
    user_id      integer generated by default as identity primary key,
    email        varchar(255),
    name         varchar(255),
    total_saved  integer
);

-- ----------------------------------------------------------------------------
-- passwords  (1-to-1 with users)
-- NOTE: passwords are currently stored in PLAIN TEXT in the source MySQL DB.
-- Migrated as-is to preserve behavior; strongly recommend hashing (e.g. via
-- Supabase Auth or bcrypt) before this goes anywhere near production.
-- ----------------------------------------------------------------------------
create table passwords (
    password_id  integer generated by default as identity primary key,
    user_id      integer unique references users(user_id),
    "password"   varchar(50)
);

-- ----------------------------------------------------------------------------
-- routes
-- ----------------------------------------------------------------------------
create table routes (
    route_id     integer generated by default as identity primary key,
    co2emitted   double precision,
    destination  varchar(255),
    origin       varchar(255),
    user_id      integer references users(user_id)
);

-- ----------------------------------------------------------------------------
-- vehicles
-- ----------------------------------------------------------------------------
create table vehicles (
    vehicle_id   integer generated by default as identity primary key,
    fuel_type    varchar(255),
    model_type   varchar(255),
    user_id      integer references users(user_id)
);

-- ----------------------------------------------------------------------------
-- waypoints
-- ----------------------------------------------------------------------------
create table waypoints (
    waypoints_id integer generated by default as identity primary key,
    latitude     double precision,
    longitude    double precision,
    sequence     integer,
    route_id     integer references routes(route_id)
);

-- ============================================================================
-- Data
-- ============================================================================

insert into users (user_id, email, name, total_saved) values
(1,'pratik@test.com','Pratik',0),
(2,'kpratik.mgmt76@hsmonline.edu.np','Owens',0),
(3,'testrunner-ecoroute@example.com','Test Runner',0),
(4,'testrunner-ecoroute2@example.com','Test Runner2',0),
(5,'luca@gmail.com','Luca',0);

insert into passwords (password_id, user_id, "password") values
(1,1,'12345'),
(4,2,'4321'),
(5,3,'TestPass123!'),
(6,4,'TestPass123!'),
(7,5,'54321');

insert into routes (route_id, co2emitted, destination, origin, user_id) values
(1,51.6258575,'Austin, TX','Dallas, TX',1),
(2,72.4581375,'San Antonio, TX','Dallas, TX',1),
(3,248.28462050000002,'San Antonio, TX','Nashville, TN',1),
(4,129.271996,'Marsielle, France','Paris, France',1),
(5,51.6258575,'Austin, TX','Dallas, TX',1),
(6,362.587939,'Amarrilo, TX','San Fransisco, CA',1),
(7,84.260519,'Dallas, TX','Little Rock, AR',1),
(8,87.12722690728259,'little rock, AR','dallas, TX',1),
(9,86.99865378680629,'dallas, TX','little rock, AR',1),
(10,84.260519,'dallas, TX','little rock, AR',1),
(11,0,'Dallas, TX','Little Rock, AR',1),
(12,51.6278315,'Austin, TX','Dallas, TX',3),
(13,458.610208,'Austin, TX','newark, NJ',5),
(14,96.34616950000002,'Amarrilo, TX','Dallas, TX',1),
(15,31.659012,'San Jose, CA','Sacramento, CA',1),
(16,31.659012,'San Jose, CA','Sacramento, CA',1);

insert into vehicles (vehicle_id, fuel_type, model_type, user_id) values
(1,'petrol','Toyota Camry',1),
(2,'diesel','Ford F150',1),
(3,'electric','Tesla ModelY',1),
(4,'petrol','Honda Civic',3),
(5,'petrol','Honda Civic',5),
(6,'petrol','Honda CRV',1),
(7,'petrol','toyota Rav4',1),
(8,'petrol','toyota Rav4',1);

-- waypoints table was empty in the source database (no rows to migrate)

-- ============================================================================
-- Re-sync identity sequences so future JPA inserts continue from the right
-- number (they currently sit at 1 after explicit-value inserts above).
-- ============================================================================
select setval(pg_get_serial_sequence('users', 'user_id'), (select coalesce(max(user_id), 1) from users), true);
select setval(pg_get_serial_sequence('passwords', 'password_id'), (select coalesce(max(password_id), 1) from passwords), true);
select setval(pg_get_serial_sequence('routes', 'route_id'), (select coalesce(max(route_id), 1) from routes), true);
select setval(pg_get_serial_sequence('vehicles', 'vehicle_id'), (select coalesce(max(vehicle_id), 1) from vehicles), true);
select setval(pg_get_serial_sequence('waypoints', 'waypoints_id'), (select coalesce(max(waypoints_id), 1) from waypoints), true);

commit;
