# Server Configuration
server.port=8080

# 1. Database Connection URL
spring.datasource.url=jdbc:mysql://localhost:3306/ecoroute?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# 2. Driver Class Name
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# 3. Credentials
spring.datasource.username=root
spring.datasource.password=Thaxaina@123

# 4. Hibernate / JPA Properties
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Third-Party API Base URLs
google.maps.api.url=https://routes.googleapis.com/
climatiq.api.url=https://api.climatiq.io/v1/

# API Keys (Read from Environment -removed curly braces so that spring reads them as direct values)
google.maps.api.key=AIzaSyCFnqZ8CfMm-8FSkWDv5ZiB74Ue_QL4Guc
climatiq.api.key=QFP0VWNC115FSFWF4EAAVPXR98
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o